Repository AlaskaAirlines/auro-flightline, pull requests merged in 2021-06, with the labels that each got.

#8 Feature cancelled segment UI update
  demo/demo.md
  package-lock.json
  src/auro-flightline.js
  src/style-flightline.scss
  test/auro-flightline.test.js
Labels: Status: Review Needed, Type: Feature

#14 fix(a11y): adds layover readout for screenreaders #13
  package-lock.json
  src/auro-flight-segment.js
  src/style-flight-segment.scss
Labels: Status: Complete and Ready to Merge, Status: Review Needed, Type: Bug

#16 fix(stop): mobile stop size decreased
  docs/api.md
  package-lock.json
  src/style-flight-segment.scss
Labels: Status: Review Needed, Type: Bug
